title: "Spatial Statistics Lab"
description: "Spatial Statistics Lab Webpage Practice"
email: "thanyou833@gmail.com"


baseurl: "/JekyllPractice"
url: "http://https://gatepsev.github.io/JekyllPractice/"
